### PR TITLE
fix: fix translation errors

### LINKED ISSUE #14: Translation errors
We'll need to address these translation errors:

Screenshot 2020-08-26 at 09 09 46

### PR DESCRIPTION
**Pull request by ismay**
Closes #14

Notes

* Best solution for the GatewayConfigFormEdit would be (the way I see it), to handle submit errors in the same way as we've done for some of the sms commands, with `hasSubmitErrors` and `submitError` and the reusable `SubmitError` component. That would mean we'd have refactor the submission hooks slightly, so I've gone with this for now, as it's a slightly faster solution. We could also show a notification on error, but in that case we shouldn't use the useCriticalNotification hook, but call addAlert from the submission hook. useCriticalNotification causes an infinite loop whenever I tried it.
* Something similar goes for the GatewayConfigList / SmsCommandList. Loading errors should probably be shown in a noticebox, whereas errors for the hooks could probably best be shown in a notification (that would require slightly different hooks, so for now I've gone for the noticebox approach for all).
* I've taken the liberty to simplify the delete gateway modal slightly, so that we don't need to worry about loading and error states. (see also the delete modal for the SmsCommandList)
* I've removed the modulenotice. It wasn't doing anything, but the translation was causing a warning. If we need it it'll be in version control.

### CODE REVIEW

File: src/views/gateway_configuration/GatewayConfigFormEdit.js [hunk 1]
```diff
@@ -26,26 +26,53 @@ export const GatewayConfigFormEdit = () => {
...
-    useCriticalNotification(saveClickatellGatewayError)
+
+    const saveError =
+        saveGenericGatewayError ||
+        saveBulkSMSGatewayError ||
+        saveClickatellGatewayError
+
+    if (loading) {
+        return (
+            <React.Fragment>
```
Comment (Mohammer5) [inline src/views/gateway_configuration/GatewayConfigFormEdit.js:55]: Could be `<>` and `</>`. I find that easier to visually recognize than reading the actual name

**Review by Mohammer5 — COMMENTED** [review]
Why did you "downgrade" the delete confirmation dialog?

File: src/views/gateway_configuration/GatewayConfigFormEdit.js (hunk 1 above)
Comment (ismay) [reply src/views/gateway_configuration/GatewayConfigFormEdit.js:55]: 👍 Reason I got used to doing this is because this way you don't need your build tooling to support this specific notation (the short fragment notation needs babel 7+). But since our build tooling supports it I guess there's no reason to stick to the old version. I'll change it.

**Comment by ismay** [comment]
> Why did you "downgrade" the delete confirmation dialog?

We talked about this on slack, but for anyone else reading this, see the notes above.

File: src/views/gateway_configuration/GatewayConfigFormEdit.js (hunk 1 above)
Comment (ismay) [reply src/views/gateway_configuration/GatewayConfigFormEdit.js]: Fixed in 026b198

**Review by Mohammer5 — APPROVED** [review]
